---
title: "HW03_Sampathirao_A"
author: "Anvita Sampathirao"
date: "5/28/2019"
output: pdf_document
---

```{r}
#1.1a. 
#Let p be the probability (lambda) of winning the game
#p*x_w-x=0
#p=1-(x/x_w)
#1.1b.
#AverageGain=(x_w*p)-x*(1-p)
AverageGain<-(1000*0.05)-10*(1-0.05)
AverageGain
#1.1c. 
#AverageGain=0
#x_w*p=x*(1-p)
p<-10/(10+1000)
p
```

```{r}
#1.2a.
GradUnemployedp<-0.009/0.046
GradUnemployedp
NGradUnemployedp<-0.037/0.046
NGradUnemployedp
#1.2b.
#For Educational achievement and employment status to be independent variables probability of their intersection should be equal to the product of their independent probabilities which is true in this case. That is:
#P(X&Y)=P(X)*P(Y)
```

```{r}
#1.3.
#P(InnerCircle)=2/3*Ar
#P(BullsEye)=5/100*Ar
#P(InnerCircle|BullsEye)=1
#P(BullsEye|InnerCircle)[Variable-Prob]=P(InnerCircle|BullsEye)*P(BullsEye)/P(InnerCircle)
Prob<-1*(5/100)*(3/2)
Prob
```

```{r}
#1.4
#P(D+)=1/1000=0.001
#P(D-)=1-0.001=0.999
#P(T+|D+)=0.95
#P(T+|D-)=0.05
#1.4a.
#P(D+|T+)=?=P(D+)*P(T+|D+)/P(T+)
#P(T+)=P(T+|D+)*P(D+)+P(T+|D-)*P(D-)
PDiseaseTestPve<-(0.001*0.95)/((0.001*0.95)+(0.05*0.999))
PDiseaseTestPve
#1.4b.
PDiseaseTestPve1<-(0.0001*0.95)/((0.0001*0.95)+(0.05*0.9999))
PDiseaseTestPve1
#1.4c.
#This tells us that for rare diseases, the chances of actually having the disease are very minimal or insignificant if the disease is extremely rare despite testing positive. 
```

```{r}
#2a.
dice<-function(n){
probability<-1/n
return(probability)
}
dice(4)
dice(20)
dice(100)
#2b.
die1 = c(1:20)
die1
library(ggplot2)
sout <- sample(die1, 1000, replace=TRUE)
ggplot(data=data.frame(sout),aes(x=sout)) + 
  geom_histogram(aes(y=..count../sum(..count..))) + 
  xlim(0, 7) + ylab("density") + xlab("outcome")
#It is a Uniform distribution, all outcomes are equally probable  and have a constant probability
#2c.
uniformfun<-function(x)
{
ifelse(x>=1&x<=20,dice(20),0)
}
uniformfun(3)
uniformfun(89)
#2d.
uniformcdf<-function(x)
{
ifelse(x>=1&x<=20,(x-1)/(20-1),0)
}
ggplot(data=data.frame(x=c(0:20)),aes(x)) + stat_function(fun=uniformcdf)
Prob1<-uniformcdf(20)-uniformcdf(14)
Prob1
#2e.
rolldice<-function(){
die2=c(1:6)
sout1<-sample(die2,4,replace=TRUE)
b<-sum(sout1)-min(sout1)
return(b)
}
sout2<-sample(rolldice(),1000,replace=TRUE)
ggplot(data=data.frame(sout2),aes(x=sout2)) + 
  geom_histogram(aes(y=..count../sum(..count..))) + 
  xlim(0, 7) + ylab("density") + xlab("outcome")
```

```{r}
#3a.
pbinom(500,size=10000,prob=(1/20),lower.tail=TRUE)
SMPL1<-sample(die1,10000,replace=TRUE)
Proportion<-sum((SMPL1==20))/10000
Proportion
#3b.
a<-rbinom(1,1000,1/100)
a
sum(a==1)
#3c.
ppois(1,5,lower.tail=FALSE)
#3d.
pnorm(85,mean=70,sd=10,lower.tail=FALSE)
pnorm(85,mean=70,sd=10,lower.tail=TRUE)-pnorm(55,mean=70,sd=10,lower.tail=TRUE)
1-pnorm(40,mean=70,sd=10,lower.tail=FALSE)
#3e.
#Normal distribution is an appropriate distribution to simulate grades for a large class strength (say 100 or more). But smaller class sizes it may not be a suitable distribution. 
```




